name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - feature
      - enhancement
  - title: "🐛 Bug Fixes"
    labels:
      - bug
      - fix
  - title: "💥 Breaking Changes"
    labels:
      - breaking
      - api-change
  - title: "🧰 Maintenance"
    labels:
      - chore
      - ci
      - build
      - test
      - style
  - title: "📝 Documentation"
    labels:
      - docs
      - documentation
  - title: "⚙️ Refactoring"
    labels:
      - refactor
  - title: "⚡ Performance"
    labels:
      - performance
      - perf
  - title: "⬆️ Dependencies"
    labels:
      - dependencies
      - deps
      - dependabot
      - renovate

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

exclude-labels:
  - skip-changelog
  - duplicate
  - invalid
  - wontfix

template: |
  ## What's Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - major
      - breaking
  minor:
    labels:
      - minor
      - feature
      - enhancement
  patch:
    labels:
      - patch
      - bug
      - fix
      - dependencies
      - docs
      - documentation
      - refactor
      - chore
  default: patch

autolabeler:
  - label: dependencies
    title:
      - '/^chore\(deps.*\):/i'
    branch:
      - '/^dependabot\//'
      - '/^renovate\//'
  - label: documentation
    files:
      - '**/*.md'
      - 'docs/**'
  - label: tests
    files:
      - 'tests/**'
  - label: ci
    files:
      - '.github/workflows/**'


