name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: write

jobs:
  build-and-publish:
    name: Build and publish python package
    runs-on: ubuntu-latest
    environment:
      name: pypi-publish
      url: https://pypi.org/p/xmltodict
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build sdist and wheel
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Upload sdist and wheel as release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
